Ucube plot
SciTools/test-iris-imagehash pull request #32
Opened 2020-03-31 17:49 UTC by pp-mo

New graphic for PoC ugrid code.
See : https://github.com/SciTools/iris/pull/3692

2020-04-01 11:32 UTC, pp-mo commented
The Travis tests are running + passing : https://travis-ci.org/github/SciTools/test-iris-imagehash/builds/669353870

We are having some problems with GitHub not reporting Travis tests : [same for Iris ...](https://github.com/SciTools/iris/pull/3692#issuecomment-607109807)

2020-04-01 14:28 UTC, trexfeathers requested changes
The diff for this includes the 19 hashes changed in #31 - @pp-mo perhaps your `ucube_plot` branch was based on a stale version of `master`?

2020-04-01 14:49 UTC, pp-mo commented
> @trexfeathers diff for this includes the 19 hashes changed in #31 ...

Good spot !
I was careless. Now fixed with rebase..
Testing OK ... https://travis-ci.org/github/SciTools/test-iris-imagehash/builds/669732069

2020-04-03 13:09 UTC, trexfeathers approved these changes

2020-04-03 13:09 UTC, trexfeathers commented
All good, thanks @pp-mo!

2020-04-03 13:10 UTC, merged